# Generated by Django 3.2.9 on 2021-11-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_sl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='xyz',
        ),
    ]
